services:
  - type: web
    name: vysorserver
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./VysorServer/Dockerfile
    dockerContext: ./VysorServer
    healthCheckPath: /status
    autoDeployTrigger: commit
